-- Phase 06 Seed Script
INSERT OR IGNORE INTO services (id, slug, name, category, short_description, status, display_order, seo_title, seo_description, is_visible, hero_heading, hero_copy, capabilities, deliverables) VALUES (
    'website-design-development', 'website-design-development', 'Website Design & Development', 'digital', 'We engineer fast, accessible, and conversion-optimized websites that serve as a robust digital foundation for your brand.', 'active', 1, 'Website Design & Development | SoftDows', 'Professional website design and development services. We build fast, responsive, and conversion-focused websites.', 1, 'Website Design & Development', 'We engineer fast, accessible, and conversion-optimized websites that serve as a robust digital foundation for your brand.', '{"heading":"Technical Capabilities","items":[{"title":"Frontend Engineering","desc":"Modern frameworks, optimized assets, and resilient UI architecture."},{"title":"CMS Integration","desc":"Headless or traditional content management tailored to your team."},{"title":"Conversion Optimization","desc":"Data-driven structural layouts that reduce user friction."}]}', NULL
  );
INSERT OR IGNORE INTO services (id, slug, name, category, short_description, status, display_order, seo_title, seo_description, is_visible, hero_heading, hero_copy, capabilities, deliverables) VALUES (
    'custom-software-web-applications', 'custom-software-web-applications', 'Custom Software & Web Applications', 'digital', 'We architect and develop tailored software systems that solve complex operational challenges and automate business logic.', 'active', 2, 'Custom Software & Web Applications | SoftDows', 'Scalable custom software and web application development designed to streamline your business operations.', 1, 'Custom Software & Web Applications', 'We architect and develop tailored software systems that solve complex operational challenges and automate business logic.', '{"heading":"Platform Features","items":[{"title":"Custom Dashboards","desc":"Real-time data visualization and operational control panels."},{"title":"API Engineering","desc":"Secure endpoints connecting your platform to third-party services."},{"title":"Database Architecture","desc":"Structured, scalable data models designed for performance."}]}', NULL
  );
INSERT OR IGNORE INTO services (id, slug, name, category, short_description, status, display_order, seo_title, seo_description, is_visible, hero_heading, hero_copy, capabilities, deliverables) VALUES (
    'ecommerce-development', 'ecommerce-development', 'eCommerce Development', 'digital', 'We build secure, high-performance online storefronts that streamline the buying process and integrate smoothly with your inventory.', 'active', 3, 'eCommerce Development | SoftDows', 'High-performance eCommerce platforms built for conversion and scalability.', 1, 'eCommerce Development', 'We build secure, high-performance online storefronts that streamline the buying process and integrate smoothly with your inventory.', '{"heading":"Store Capabilities","items":[{"title":"Custom Storefronts","desc":"Tailored shopping experiences built on modern frameworks."},{"title":"Inventory Integration","desc":"Synchronization with your existing ERP or management tools."},{"title":"Performance Optimization","desc":"Technical audits and caching strategies to maximize speed."}]}', NULL
  );
INSERT OR IGNORE INTO services (id, slug, name, category, short_description, status, display_order, seo_title, seo_description, is_visible, hero_heading, hero_copy, capabilities, deliverables) VALUES (
    'ui-ux-design', 'ui-ux-design', 'UI & UX Design', 'digital', 'Intuitive user interface and experience design that reduces friction and builds brand trust.', 'active', 4, 'UI/UX Design | SoftDows', 'Professional User Interface and User Experience design services.', 1, 'UI & UX Design', 'Intuitive user interface and experience design that reduces friction and builds brand trust.', '{"heading":"Design Capabilities","items":[{"title":"Wireframing & Prototyping","desc":"Structural mapping of platform flow before engineering begins."},{"title":"Design Systems","desc":"Scalable component libraries for consistent brand application."},{"title":"Interface Design","desc":"Polished, modern visual execution of digital platforms."}]}', NULL
  );
INSERT OR IGNORE INTO services (id, slug, name, category, short_description, status, display_order, seo_title, seo_description, is_visible, hero_heading, hero_copy, capabilities, deliverables) VALUES (
    'seo-digital-visibility', 'seo-digital-visibility', 'SEO & Digital Visibility', 'digital', 'We build the technical foundation and structured content necessary for sustained organic discoverability.', 'active', 5, 'SEO & Digital Visibility | SoftDows', 'Technical SEO and digital visibility strategies to improve organic search rankings.', 1, 'SEO & Digital Visibility', 'We build the technical foundation and structured content necessary for sustained organic discoverability.', '{"heading":"Optimization Areas","items":[{"title":"Technical SEO","desc":"Ensuring your platform is easily crawlable and indexable."},{"title":"Performance Tuning","desc":"Speed optimizations that directly impact search ranking."},{"title":"Structured Data","desc":"Implementing schema to enhance search engine understanding."}]}', NULL
  );
INSERT OR IGNORE INTO services (id, slug, name, category, short_description, status, display_order, seo_title, seo_description, is_visible, hero_heading, hero_copy, capabilities, deliverables) VALUES (
    'website-maintenance-support', 'website-maintenance-support', 'Maintenance & Support', 'digital', 'Ongoing technical oversight, security updates, and performance monitoring to protect your digital investment.', 'active', 6, 'Website Maintenance & Support | SoftDows', 'Ongoing technical support and maintenance to ensure platform reliability and security.', 1, 'Maintenance & Support', 'Ongoing technical oversight, security updates, and performance monitoring to protect your digital investment.', '{"heading":"Support Services","items":[{"title":"Security Updates","desc":"Regular patching of dependencies and core systems."},{"title":"Performance Monitoring","desc":"Tracking load times and resolving degradation."},{"title":"Technical Support","desc":"Direct access to engineers for troubleshooting and updates."}]}', NULL
  );
INSERT OR IGNORE INTO services (id, slug, name, category, short_description, status, display_order, seo_title, seo_description, is_visible, hero_heading, hero_copy, capabilities, deliverables) VALUES (
    'domain-registration-management', 'domain-registration-management', 'Domain Registration & Management', 'digital', 'Secure your brand''s digital identity with our professional domain management services. We provide reliable registration, renewal, and DNS management infrastructure.', 'active', 7, 'Domain Registration & Management | SoftDows', 'Professional domain registration and DNS management infrastructure.', 1, 'Domain Registration & Management', 'Secure your brand''s digital identity with our professional domain management services. We provide reliable registration, renewal, and DNS management infrastructure.', '{"heading":"Core Capabilities","items":[{"title":"Domain Registration","desc":"Acquire the right digital property for your brand."},{"title":"DNS Management","desc":"Configure routing, email, and subdomains securely."},{"title":"Renewal Management","desc":"Prevent accidental expiration of critical domains."}]}', NULL
  );
INSERT OR IGNORE INTO services (id, slug, name, category, short_description, status, display_order, seo_title, seo_description, is_visible, hero_heading, hero_copy, capabilities, deliverables) VALUES (
    'managed-web-hosting', 'managed-web-hosting', 'Managed Web Hosting', 'digital', 'High-performance, fully managed web hosting infrastructure designed for demanding business applications and optimal uptime.', 'active', 8, 'Managed Web Hosting | SoftDows', 'High-performance, secure, and fully managed web hosting infrastructure.', 1, 'Managed Web Hosting', 'High-performance, fully managed web hosting infrastructure designed for demanding business applications and optimal uptime.', '{"heading":"Hosting Features","items":[{"title":"Managed Environments","desc":"Server configuration, patching, and maintenance handled by our team."},{"title":"Speed & Optimization","desc":"Tuned infrastructure for rapid response times."},{"title":"Security","desc":"Active monitoring, firewalls, and regular backups."}]}', NULL
  );
INSERT OR IGNORE INTO software_products (id, slug, name, short_name, tagline, short_description, full_description, status, featured, is_visible, display_order, target_audience, problem, capabilities, key_benefits, primary_cta, external_url, seo_title, seo_description) VALUES (
    'biddalok', 'biddalok', 'Biddalok', 'Biddalok', 'Structured Institutional Management', 'Comprehensive school administration platform for academic workflows.', 'Biddalok is a structured institutional management platform designed to streamline school administration. It connects students, teachers, and administrators through unified academic workflows and reporting systems.', 'active', 1, 1, 1, 'Schools, educational institutions, and academic administrators.', 'Fragmented academic data, manual administrative workflows, and disconnected communication between teachers and students.', '["School Administration","Academic Workflows","Student & Teacher Management","Comprehensive Reports","Structured Institutional Management"]', '["Centralized Academic Data","Reduced Administrative Overhead","Clear Operational Visibility"]', '{"label":"Request Demo","url":"/contact/"}', NULL, 'Biddalok | School Administration Platform | SoftDows', 'Biddalok is a comprehensive school administration platform by SoftDows for managing students, teachers, and academic workflows.'
  );
INSERT OR IGNORE INTO software_products (id, slug, name, short_name, tagline, short_description, full_description, status, featured, is_visible, display_order, target_audience, problem, capabilities, key_benefits, primary_cta, external_url, seo_title, seo_description) VALUES (
    'eduweb', 'eduweb', 'EduWeb', 'EduWeb', 'Educational Technology Software', 'Specialized educational software infrastructure engineered by SoftDows.', 'EduWeb is an educational technology software product engineered by SoftDows. It is built to support robust digital infrastructure within academic environments.', 'upcoming', 0, 1, 2, NULL, NULL, '[]', '[]', '{"label":"Enquire About EduWeb","url":"/contact/"}', NULL, 'EduWeb | Educational Software | SoftDows Products', 'EduWeb is a specialized educational software product developed by SoftDows.'
  );
INSERT OR IGNORE INTO software_products (id, slug, name, short_name, tagline, short_description, full_description, status, featured, is_visible, display_order, target_audience, problem, capabilities, key_benefits, primary_cta, external_url, seo_title, seo_description) VALUES (
    'smarttutor', 'smarttutor', 'SmartTutor', 'SmartTutor', 'Learning Management Architecture', 'Digital learning platform architecture built for educational delivery.', 'SmartTutor is a specialized digital learning product developed by SoftDows. It is designed to provide structured architecture for digital educational delivery.', 'upcoming', 0, 1, 3, NULL, NULL, '[]', '[]', '{"label":"Enquire About SmartTutor","url":"/contact/"}', NULL, 'SmartTutor | Learning Platform | SoftDows Products', 'SmartTutor is a digital learning software product developed by SoftDows.'
  );
INSERT OR IGNORE INTO software_products (id, slug, name, short_name, tagline, short_description, full_description, status, featured, is_visible, display_order, target_audience, problem, capabilities, key_benefits, primary_cta, external_url, seo_title, seo_description) VALUES (
    'mymosque', 'mymosque', 'myMosque', 'myMosque', 'Structured Community Management', 'Operational platform for mosque administration and community management.', 'myMosque provides structured management tools for modern mosque administration. It helps operational teams manage facilities, catchment-area users, and community operations from a single platform.', 'active', 1, 1, 4, 'Mosque administrators, community leaders, and operational staff.', 'Lack of structured operational tools for managing mosque facilities and community engagement.', '["Mosque Management","Administration Tools","Community Engagement","Operations Management","Catchment-Area User Support"]', '["Streamlined Operations","Improved Community Connection","Professional Administration"]', '{"label":"Request Demo","url":"/contact/"}', NULL, 'myMosque | Mosque Management Platform | SoftDows', 'myMosque is a structured operational platform by SoftDows for mosque administration and community management.'
  );
INSERT OR IGNORE INTO software_products (id, slug, name, short_name, tagline, short_description, full_description, status, featured, is_visible, display_order, target_audience, problem, capabilities, key_benefits, primary_cta, external_url, seo_title, seo_description) VALUES (
    'experthunter', 'experthunter', 'ExpertHunter', 'ExpertHunter', 'Professional Discovery Platform', 'Platform architecture for professional discovery and connection.', 'ExpertHunter is a professional software platform developed by SoftDows. It provides the structured architecture necessary to connect organizations with specialized professionals.', 'upcoming', 0, 1, 5, NULL, NULL, '[]', '[]', '{"label":"Enquire About ExpertHunter","url":"/contact/"}', NULL, 'ExpertHunter | Professional Discovery | SoftDows Products', 'ExpertHunter is a specialized software platform developed by SoftDows.'
  );
INSERT OR IGNORE INTO software_products (id, slug, name, short_name, tagline, short_description, full_description, status, featured, is_visible, display_order, target_audience, problem, capabilities, key_benefits, primary_cta, external_url, seo_title, seo_description) VALUES (
    'easywebdev', 'easywebdev', 'EasyWebDev', 'EasyWebDev', 'Web Engineering Tools', 'Software tooling and platform architecture for web engineering.', 'EasyWebDev is a specialized software product developed by SoftDows, providing structural tooling and resources for web development operations.', 'upcoming', 0, 1, 6, NULL, NULL, '[]', '[]', '{"label":"Enquire About EasyWebDev","url":"/contact/"}', NULL, 'EasyWebDev | Web Engineering | SoftDows Products', 'EasyWebDev is a web engineering software product developed by SoftDows.'
  );
INSERT OR IGNORE INTO ventures (id, slug, brand_name, local_name, category, short_description, full_description, status, featured, is_visible, display_order, external_url, audience, softdows_role, key_focus, seo_title, seo_description) VALUES (
    'banglanotice', 'banglanotice', 'BanglaNotice', 'বাংলা নোটিশ', 'Information Portal', 'Bengali information and publication platform.', 'A comprehensive Bengali information and publication platform covering crucial areas such as education, public notices, public-service information, jobs, and related useful daily information for the Bengali-speaking audience.', 'active', 1, 1, 1, 'https://banglanotice.com', 'Bengali speakers seeking reliable public information.', 'Owned & Operated Platform', '["Education","Public Notices","Jobs","Service Information"]', 'BanglaNotice | A SoftDows Venture', 'BanglaNotice is a Bengali information platform covering education, notices, and public-service information.'
  );
INSERT OR IGNORE INTO ventures (id, slug, brand_name, local_name, category, short_description, full_description, status, featured, is_visible, display_order, external_url, audience, softdows_role, key_focus, seo_title, seo_description) VALUES (
    'bidyashikhi', 'bidyashikhi', 'BidyaShikhi', 'বিদ্যাশিখি', 'EdTech / Learning', 'Bengali-language learning and skill-development platform.', 'An educational initiative focused on providing accessible learning resources and skill-development materials in the Bengali language, helping individuals enhance their capabilities and academic knowledge.', 'active', 1, 1, 2, 'https://bidyashikhi.com', 'Students and professionals seeking skill development in Bengali.', 'Owned & Operated Platform', '["Skill Development","Academic Resources","Language Learning"]', 'BidyaShikhi | A SoftDows Venture', 'BidyaShikhi is a Bengali-language learning and skill-development platform.'
  );
INSERT OR IGNORE INTO ventures (id, slug, brand_name, local_name, category, short_description, full_description, status, featured, is_visible, display_order, external_url, audience, softdows_role, key_focus, seo_title, seo_description) VALUES (
    'nicetrix', 'nicetrix', 'NiceTrix', 'নাইস ট্রিক্স', 'Content Platform', 'Content platform for practical lifestyle, tech, and academic guides.', 'A versatile content platform covering practical, everyday topics including lifestyle improvements, academics, AI/technology trends, career advice, and related actionable guides.', 'active', 1, 1, 3, 'https://nicetrix.com', 'General readers looking for practical guides and technology insights.', 'Owned & Operated Platform', '["Technology","Lifestyle","Career Guides","AI"]', 'NiceTrix | A SoftDows Venture', 'NiceTrix is a content platform covering practical lifestyle, technology, and career guides.'
  );
INSERT OR IGNORE INTO ventures (id, slug, brand_name, local_name, category, short_description, full_description, status, featured, is_visible, display_order, external_url, audience, softdows_role, key_focus, seo_title, seo_description) VALUES (
    'gulfhive', 'gulfhive', 'GulfHive', NULL, 'Platform', 'Upcoming regional platform.', 'An upcoming platform currently under active development. More details will be published upon verified launch.', 'hidden', 0, 0, 4, NULL, 'Regional audience.', 'Owned & Operated Platform', '[]', 'GulfHive | A SoftDows Venture', 'GulfHive is an upcoming platform by SoftDows.'
  );
INSERT OR IGNORE INTO ventures (id, slug, brand_name, local_name, category, short_description, full_description, status, featured, is_visible, display_order, external_url, audience, softdows_role, key_focus, seo_title, seo_description) VALUES (
    'baharimart', 'baharimart', 'BahariMart', 'বাহারি মার্ট', 'eCommerce', 'Modern eCommerce platform.', 'An eCommerce platform designed to provide a seamless and reliable shopping experience for a variety of consumer goods.', 'active', 1, 1, 5, 'https://baharimart.com', 'Online shoppers.', 'Owned & Operated Platform', '["Consumer Retail","Seamless Checkout","Digital Commerce"]', 'BahariMart | A SoftDows Venture', 'BahariMart is a modern eCommerce platform operated by SoftDows.'
  );
INSERT OR IGNORE INTO team_members (id, name, role, bio, display_order, status, slug, display_name, short_bio, full_bio, monogram_fallback, expertise, skills, experience, education, certifications, languages, email, phone, website, linkedin, github, featured, is_visible, seo_title, seo_description) VALUES (
    'ansar-ahammad', 'Ansar Ahammad', 'Founder', 'Ansar Ahammad is the Founder of SoftDows, focusing on practical digital solutions designed around business needs, usability, maintainability and long-term value.', 1, 'active', 'ansar-ahammad', 'Ansar Ahammad', 'Ansar Ahammad is the Founder of SoftDows, focusing on practical digital solutions designed around business needs, usability, maintainability and long-term value.', 'Ansar Ahammad established SoftDows to bridge the gap between complex engineering and practical business operations. With a strong commitment to clean architecture and user-centric design, he ensures that every project is engineered for tangible business outcomes rather than just technical novelty. His approach emphasizes transparency, reliability, and long-term scalability.', 'AA', '["Digital Strategy","Systems Architecture","Business Operations","Product Engineering"]', '[]', '[{"title":"Founder","company":"SoftDows","period":"Present","description":"Leading digital engineering and technical strategy for clients and internal ventures."}]', '[]', '[]', '["Bengali","English"]', NULL, NULL, NULL, NULL, NULL, 1, 1, 'Ansar Ahammad | Founder at SoftDows', 'Ansar Ahammad is the Founder of SoftDows, focusing on practical digital solutions designed around business needs and maintainability.'
  );
